"use client";
import Link from "next/link";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { iconPaths } from "@/lib/icons";
import type { IconName } from "@/lib/types";

export default function Home() {
  const [chosen, setChosen] = useState<IconName>("calendar");
  const samples: IconName[] = ["calendar", "bell", "home", "search", "settings"];
  return <main className="app-shell"><div className="hero"><nav className="landing-nav"><Link href="/" className="brand"><span className="brand-mark">IF</span> IconForge</Link><div style={{ display: "flex", gap: 8 }}><Link href="/app/sets" className="btn btn-quiet">Icon sets</Link><Link href="/create" className="btn btn-primary">Open workspace <ArrowRight size={15} /></Link></div></nav><section className="hero-grid"><div><div className="eyebrow">The consistent icon generator</div><h1>Build icons that belong together.</h1><p className="hero-copy">Generate clean SVG icons from text and keep your entire icon set visually consistent.</p><div style={{ marginTop: 30 }}><Link href="/create" className="btn btn-primary">Create an icon <ArrowRight size={15} /></Link></div></div><div className="example"><div className="example-head"><span>calendar with notification badge</span><span className="muted">6 variations</span></div><div className="example-stage" dangerouslySetInnerHTML={{ __html: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${iconPaths[chosen]}<circle cx="18" cy="6" r="3" fill="currentColor" stroke="none"/></svg>` }} /><div className="example-row">{samples.map((sample) => <button key={sample} onClick={() => setChosen(sample)} aria-label={`Preview ${sample}`} className={chosen === sample ? "selected" : ""} dangerouslySetInnerHTML={{ __html: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${iconPaths[sample]}</svg>` }} />)}</div><div style={{ marginTop: 18, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span className="style-chip"><LockKeyhole size={13} /> Style locked</span><span className="muted" style={{ fontSize: 11 }}>24 × 24 · 1.5 px</span></div></div></section><section className="section-rule"><div><div className="eyebrow">One visual language</div><h2 style={{ margin: "10px 0", fontSize: 27, letterSpacing: "-.05em" }}>A set that feels authored.</h2><p className="muted" style={{ maxWidth: 390, lineHeight: 1.55, fontSize: 14 }}>Lock the character of one icon, then carry its weight, rhythm, and geometry through everything that follows.</p></div><div className="set-preview"><span className="muted" style={{ fontSize: 12 }}>Finance Icons</span>{["wallet", "card", "chart", "bank", "receipt"].map((name) => <span key={name} dangerouslySetInnerHTML={{ __html: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${iconPaths[name as keyof typeof iconPaths]}</svg>` }} />)}</div></section></div></main>;
}
